# Generated by Django 3.2.16 on 2024-02-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpstracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='xcoordination',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='courier',
            name='ycoordination',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
